In [5]:
import torch
import torchvision ## suport para imagens 
import torchaudio


In [4]:
!pip install --user torch torchvision torchaudio -f https://download.pytorch.org/whl/cu111/torch_stable.html

Looking in links: https://download.pytorch.org/whl/cu111/torch_stable.html

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [8]:
array = [[1,2,3], [3,2,1]]

tensor = torch.tensor(array)

print(tensor)

tensor([[1, 2, 3],
        [3, 2, 1]])


In [12]:
import numpy as np

np_array = np.array(array)
np_tensor = torch.from_numpy(np_array) 
print(np_array)

[[1 2 3]
 [3 2 1]]


In [13]:
tensor.shape

torch.Size([2, 3])

In [14]:
tensor.dtype

torch.int64

In [16]:
tensor.device

device(type='cpu')

In [17]:
## Aprendizado de maquina profundo requer uma GPU que em recursos de computação paralela, tempos mais rapidos e 
## desempenho

In [19]:
a = torch.tensor([[1,1], [2,2]])
b = torch.tensor([[2,2], [3,3]])

print(a + b)

tensor([[3, 3],
        [5, 5]])


In [21]:
a = torch.tensor([[1,1], [2,2]])
c = torch.tensor([[2,2,4], [3,3,5]])

print(a + c)


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [22]:
print(a*b)

tensor([[2, 2],
        [6, 6]])


In [24]:
import torch.nn as nn


input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])


In [25]:
linear_layer = nn.Linear(in_features=3, out_features=2)

In [26]:
output = linear_layer(input_tensor)
print(output)

tensor([[ 0.2537, -0.2949]], grad_fn=<AddmmBackward0>)


In [27]:
linear_layer.weight

Parameter containing:
tensor([[-0.5336,  0.2483, -0.4188],
        [ 0.3507, -0.1061, -0.0980]], requires_grad=True)

In [28]:
linear_layer.bias

Parameter containing:
tensor([ 0.2273, -0.3915], requires_grad=True)

#### Qual e a operação usada :
$$
    y_0 = W_0 \cdot X + b_0
$$
* X input array
* W weight (peso)
* b bias (vies)


#### Obs 
* Redes apenas com camadas lineares são chamadas de redes totalmente conectadas

In [29]:
model = nn.Sequential(
    nn.Linear(10, 18),
    nn.Linear(18,20),
    nn.Linear(20, 5)
)

In [30]:
input_tensor = torch.tensor([[-0.014, 0.4038, 1.0305, 0.7521, 0.7489, -0.3968, 0.0113, -1.3844, 0.8705, -0.9743]])

In [31]:
out = model(input_tensor)
print(out)

tensor([[ 0.1829, -0.0460,  0.6829, -0.1421, -0.0081]],
       grad_fn=<AddmmBackward0>)
